### ISSUE TITLE
Issues encountered when installing it

### ISSUE THREAD

**Issue by Zero3K** [0xda568/uwd-oss#1]
![image](https://github.com/0xda568/uwd-oss/assets/6194332/05a09c1d-07d4-4ec3-aee9-6f1e99130e34)

As you can see in that image, it says it copied the dll (which it actually didn't) and it is also having trouble changing the registry key. I am running it under Windows 10 21H2.

**Comment by 0xda568** [comment]
Hi, uwd-oss.dll gets automatically deleted from System32/ if a error is encountered.

The error here is: "ERROR: Access is denied". Did you try to start the script as an Administrator?

**Comment by Zero3K** [comment]
Yes, I ran it under an Administrator account.

**Comment by 0xda568** [comment]
Okay, it seems like you don't have permissions the edit the registry whatsoever. Now you could try to [give yourself permissions](https://www.groovypost.com/howto/take-full-permissions-control-edit-protected-registry-keys/) to edit **Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID{ab0b37ec-56f6-4a0e-a8fd-7a8bf7c2da96}\InProcServer32**.

Additionally, once you are in the registry, you can also try to perform the [manual installation](https://github.com/0xda568/uwd-oss/blob/main/README.md#manual-installation), which I added to the README.

**Comment by Zero3K** [comment]
https://forums.mydigitallife.net/threads/change-ownership-of-registry-key-through-command-line.79928/

**Comment by 0xda568** [comment]
Cool software, I should also consider adding a ACL modifying component to uwd-oss.

**Comment by Zero3K** [comment]
Regini is already included in Windows 10.

**Comment by 0xda568** [comment]
Oh you're right, I'm gonna simply add regini to the script if it works

**Comment by Zero3K** [comment]
It worked for me. I made a acl.txt with the following and then ran regini acl.txt:

\Registry\machine\software\classes\CLSID\{ab0b37ec-56f6-4a0e-a8fd-7a8bf7c2da96}\InProcServer32 [19 3] (so the SYSTEM account can read it and any administrator account can both read and write to any keys in that registry folder).

**Comment by 0xda568** [comment]
Excellent, I will include this in the script! Thanks for the feedback!
