### ISSUE TITLE
The batch hangs after restarting Explorer

### ISSUE THREAD

**Issue by Zero3K** [0xda568/uwd-oss#3]
It happens both when installing and uninstalling it via a Command Prompt and when running via Windows Explorer.

**Comment by 0xda568** [comment]
Is it the commandline unresponsive or do you mean that the script is still running?  The current installer.bat has PAUSE at the end, which means that it's waiting for a key input to terminate.

**Comment by Zero3K** [comment]
It doesn't have the normal press any key to continue message and pressing any key doesn't exit out of it.

**Comment by 0xda568** [comment]
That's weird. Which Windows version are you running?

**Comment by Zero3K** [comment]
Windows 10

**Comment by Zero3K** [comment]
Oh, I see that you fixed it by changing pause to exit /b. That is fine.

**Comment by 0xda568** [comment]
Thank you very much for all the feedback!
