### ISSUE TITLE
Issue with the DLL under Windows 7

### ISSUE THREAD

**Issue by Zero3K** [0xda568/uwd-oss#6]
It isn't being loaded into memory even though it is set to be used in place of explorerframe.dll via the registry key that is mentioned.

EDIT: I compiled it as 32-bit. Now it is loading but it is causing Explorer to crash. Here's what debugging with VS 2019 shows:

![image](https://github.com/0xda568/uwd-oss/assets/6194332/3f9c65d9-5571-4f37-9d09-9cb94b857b11)

**Comment by Zero3K** [comment]
Here's a stack trace that I got by attaching WinDbg to the VM:

[uwd-oss-memory-corruption-win7.log](https://github.com/0xda568/uwd-oss/files/13064388/uwd-oss-memory-corruption-win7.log)

**Comment by Zero3K** [comment]
Any news?

**Comment by 0xda568** [comment]
The software was not tested on Windows 7 and I am not planning to implement compatibility for Windows versions older than Windows 10.

**Comment by Zero3K** [comment]
Maybe someone else can do that.

**Comment by darkralts** [comment]
what is the default value for CLSID{ab0b37ec-56f6-4a0e-a8fd-7a8bf7c2da96}\InProcServer32? i set it on windows 7 now everything is broken, i would like to restore my pc functionality.
